services:
  cartservice:
    build:
      dockerfile: CartService/Dockerfile
      context: .
    ports:
      - "7010:8080"
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:8080;https://+:7070;
       - RedisConfig__ConnectionString=valkey

  orderservice:
    build:
      dockerfile: OrderService/Dockerfile
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MQConfig__HostAddress=rabbitmq
      - ConnectionStrings__Host=Server=sqlserver;
      - ConnectionStrings__User=user=orderManager;
      - ConnectionStrings__Password=password=totallynotamangerpassword!@#$5;
      - MongoDb__HostAddress=mongodb://mongodb
      - ASPNETCORE_URLS=http://+:8080;https://+:7070;
    ports:
      - "5138:8080"
    depends_on:
      - rabbitmq
      - sqlserver
      - mongodb

  identityservice:
    build:
      dockerfile: IdentityService/Dockerfile
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Host=Server=sqlserver;
      - ConnectionStrings__User=user=identityManager;
      - ConnectionStrings__Password=password=totallynotamangerpassword!@#$5;
      - ASPNETCORE_URLS=http://+:8080;https://+:7070;
    ports:
      - "5156:8080"
    depends_on:
      - sqlserver

  ocelotservice:
    build:
      dockerfile: OcelotGateway/Dockerfile
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=http://+:8080;
    ports:
      - "5044:8080"


  productservice:
    build:
      dockerfile: ProductService/Dockerfile
      context: .
    ports:
      - "7107:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MQConfig__HostAddress=rabbitmq
      - ConnectionStrings__Host=Server=sqlserver;
      - ConnectionStrings__User=user=productManager;
      - ConnectionStrings__Password=password=totallynotamangerpassword!@#$5;
      - ASPNETCORE_URLS=http://+:8080;https://+:7070;

    depends_on:
      rabbitmq:
        condition: service_started
      mongodb:
        condition: service_started
      sqlserver:
        condition: service_started

  rabbitmq:
    image: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 1
  sqlserver:
    build:
      dockerfile: sqlserver-docker
      context: .
      secrets:
        - sqlpassword
    environment:
      ACCEPT_EULA: "Y"

    ports:
      - "1434:1433"
    secrets:
      - sqlpassword

  mongodb:
    image: mongo:7.0.9
    ports:
      - "27017:27017"
    # environment:

  valkey:
    image: valkey/valkey:7.2.5
    ports:
      - "6379:6379"

secrets:
  sqlpassword:
    file: sqlpassword.txt
