# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    paths:
      - ProductService/**
      - Tests/ProductService.Tests/**
      - IdentityService/**
      - Tests/IdentityService.Tests/**
      - CartService/**
      - Tests/CartService.Tests/**
      - OrderService/**
      - Tests/OrderService.Tests/**
      - ImageService/**
      - Tests/ImageService/**
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
# no reason to split into separate flows since it is used rarely
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Test Product
      run: dotnet test Tests/ProductService.Tests/ProductService.Tests.csproj
    - name: Test Identity
      run: dotnet test Tests/IdentityService.Tests/IdentityService.Tests.csproj
    - name: Test Cart
      run: dotnet test Tests/CartService.Tests/CartService.Tests.csproj
    - name: Test Order
      run: dotnet test Tests/OrderService.Tests/OrderService.Tests.csproj
    - name: Test Image
      run: dotnet test Tests/ImageService.Tests/ImageService.Tests.csproj
