# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    paths:
      - ProductService
      - ProductService.Tests
      - IdentityService
      - IdentityService.Tests
      - CartService
      - CartService.Tests
      - OrderService
      - OrderService.Tests
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Test Product
      run: dotnet test ProductService.Tests/ProductService.Tests.csproj --verbosity normal
    - name: Test Identity
      run: dotnet test IdentityService.Tests/IdentityService.Tests.csproj --verbosity normal
    - name: Test Cart
      run: dotnet test CartService.Tests/CartService.Tests.csproj --verbosity normal
    - name: Test Order
      run: dotnet test OrderService.Tests/OrderService.Tests.csproj --verbosity normal
