name: Playwright Tests
on:
  workflow_run:
    workflows: [gh-pages]
    types: completed
  # push:
  #   branches: [main, master]
  #   paths:
  #     - UserClient/**
  #     - UserClient.Tests/**
  #     - .github/workflows/playwright.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
        working-directory: UserClient.Tests
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: UserClient.Tests
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: UserClient.Tests
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: UserClient.Tests/playwright-report/
          retention-days: 7
