name: Playwright Tests
on:
  push:
    branches: [main, master]
    paths:
      - UserClient/**
      - UserClient.Tests/**
      - .github/workflows/playwright.yml
  pull_request:
    branches: [main, master]
jobs:
  runlocalclient:
    timeout-minutes: 1
    runs-on: ubuntu-latest
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Move to client tests directory
        run: cd UserClient.Tests
      - name: Install dependencies
        run: npm ci
        working-directory: UserClient.Tests
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: UserClient.Tests

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: UserClient.Tests

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
